version: '3.9'

services:
  pg:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5437:5432"
    volumes:
      - ./_data/pg/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:6
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server --address :10123 --console-address ":10124" /data/minio
    expose:
      - "10123"
      - "10124"
    ports:
      - "10123:10123"
      - "10124:10124"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:10123/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./_data/s3:/data

  pgadmin:
    image: dpage/pgadmin4:7.7
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 9656
    ports:
      - "9656:9656"
    volumes:
      - ./_data/pgadmin:/var/lib/pgadmin
